### ISSUE TITLE
建议：能不能将保存图片默认save.png改成${spine文件名}.png

### ISSUE THREAD

**Issue by mshmznz** [anosu/Spine-Viewer#2]
拖入一个spine保存一张图片，但是默认都是save.png，每次都要手动复制spine文件名进去，如果几百上千个pine  一个个复制文件名再粘贴保存图片那太麻烦了

但是默认以spine文件名保存图片那就轻松很多了，直接保存就行了，我觉得添加这个会让大伙保存图片更方便，所以能不能考虑一下这个修改点？

-----
抱歉我说的是 Spine Viewer-vue  但是我发错版块了

**Comment by anosu** [comment]
👌
